sudo: false

language: python

# TODO: restore two guards below before merge
# (only want to upload packages from master)
stages:
  - test
  - name: conda_package
#    if: branch = master AND type != pull_request
  - name: pypi_package
#    if: branch = master AND type != pull_request

jobs:
  fast_finish: true
  include:
    - &tests
      stage: test
      python: 3.6
      env: TOX_ENV=py36
      install:
        - pip install tox
      script:
        - tox -e $TOX_ENV

    - <<: *tests
      python: 2.7
      env: TOX_ENV=py27

    - stage: conda_package
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda update conda
        - conda install "conda-build=3.0.25" anaconda-client
      script:
        - conda build conda.recipe/
        - anaconda -t $CONDA_UPLOAD_TOKEN upload --force -u cball $HOME/miniconda/conda-bld/noarch/autover*.tar.bz2

    - <<: *tests
      stage: pypi_package
      install:
      script:
      # could instead use real pypi when tag is release style
      deploy:
        provider: pypi
        server: https://test.pypi.org/legacy/
        distributions: "sdist bdist_wheel"
        user: ${TESTPYPI_USERNAME}
        password: ${TESTPYPI_PASSWORD}
        on:
          tags: true
