language: python

git:
  depth: 200

# TODO: add appropriate guards (e.g. only deploy on tag matching
# certain pattern) once auto packaging is figured out.

stages:
  - test
  - name: conda_package
#    if: (branch = master AND type != pull_request) OR (tag IS present)
  - name: pypi_package
    if: tag IS present

jobs:
  fast_finish: true
  include:
    - &tests
      stage: test
      python: 3.6
      env:
        - DESC="from current repo"
        - TOX_ENV=py36
        - MODULE=autover
      before_install:
        - pip install pyct tox
      install: true
      script:
        - doit original_script --example=$MODULE

    - <<: *tests
      env:
        - DESC="from release tag"
        - TOX_ENV=py36
        - MODULE=autover
      install:
        - doit release_tag

    - <<: *tests
      env:
        - DESC="from release tag plus commits"
        - TOX_ENV=py36
        - MODULE=autover
      install:
        - doit release_tag
        - doit after_tag

    - <<: *tests
      env:
        - DESC="from prerelease tag"
        - TOX_ENV=py36
        - MODULE=autover
      install:
        - doit prerelease_tag

    - <<: *tests
      env:
        - DESC="from prerelease tag plus commits"
        - TOX_ENV=py36
        - MODULE=autover
      install:
        - doit prerelease_tag
        - doit after_tag


##############################


    - &example_tests
      stage: test
      python: 3.6
      env:
        - DESC="example"
        - TOX_ENV=py36
        - MODULE=pkg_depend
        - EXTRA="--dir=/tmp/123"
      before_install:
        - mkdir /tmp/123
        - pip install pyct tox
        - doit $EXTRA copy_example_project --example=$MODULE
        - doit $EXTRA git_init
      install:
        - pip install -e .
        # build package so it's available for tox
        - python setup.py bdist_wheel
      script:
        - doit $EXTRA original_script --example=$MODULE


    - <<: *example_tests
      env:
        - DESC="example auto dl"
        - TOX_ENV=py36
        - MODULE=pkg_depend
        - EXTRA="--dir=/tmp/123"
      install:
        # build package so it's available for tox
        - python setup.py bdist_wheel

    - <<: *example_tests
      env:
        - DESC="example"
        - TOX_ENV=py36
        - MODULE=pkg_bundle
        - EXTRA="--dir=/tmp/123"
      install: true

    - <<: *example_tests
      env:
        - DESC="example pip+git"
        - TOX_ENV=py36
        - MODULE=pkg_depend
        - EXTRA="--dir=/tmp/123"
      install:
        - pip install git+file://tmp
      script:
        - doit $EXTRA verify_installed_version --example=$MODULE

    - <<: *example_tests
      env:
        - DESC="example pip+git"
        - TOX_ENV=py36
        - MODULE=pkg_bundle
        - EXTRA="--dir=/tmp/123"
      install:
        - pip install git+file://$HOME/$MODULE
      script:
        - doit $EXTRA verify_installed_version --example=$MODULE

    - stage: conda_package
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda update conda
        - conda install conda-build anaconda-client
      script:
        - conda build conda.recipe
      after_success:
        - export LABEL="--label dev" && [[ ! -z "$TRAVIS_TAG" ]] && LABEL=""
#        - anaconda --token $CONDA_UPLOAD_TOKEN upload --user cball ${LABEL} $(conda build --output conda.recipe)

    - <<: *tests
      stage: pypi_package
      install: true
      script: true
      deploy:
        provider: pypi
        # could instead use real pypi when tag is release style
        server: https://test.pypi.org/legacy/
        distributions: "sdist bdist_wheel"
        user: ${PYPI_USERNAME}
        password: ${PYPI_PASSWORD}
        skip_cleanup: true
