sudo: false

language: python

stages:
  - test
  - name: conda_package
# TODO: restore below before merge
#    if: branch = master AND type != pull_request

jobs:
  fast_finish: true
  include:
    - &tests
      stage: test
      python: 3.6
      env: TOX_ENV=py36
      install:
        - pip install tox
      script:
        - tox -e $TOX_ENV

    - <<: *tests
      python: 2.7
      env: TOX_ENV=py27

    - stage: conda_package
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda update conda
        - conda install "conda-build=3.0.25" anaconda-client
      script:
        - conda build conda.recipe/
        - anaconda -t $CONDA_UPLOAD_TOKEN upload --force -u cball $HOME/miniconda/conda-bld/noarch/autover*.tar.bz2

# TODO: can't test til on master
# TODO: need autover owner password
#deploy:
#  provider: pypi
#  distributions: "sdist bdist_wheel"
#  on:
#    tags: true
#  user: ?
#  password:
#    secure: ?
