{% set sdata = load_setup_py_data() %}

package:
  name: pkg_depend
  version: {{ sdata['version'] }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - autover
  run:
    - python
    # autover is listed in setup.py install_requires; when the console
    # script (tmpverify) is run, python will attempt to install
    # autover if autover's not already installed. Therefore, make
    # runtime dependency explicit here. (Alternative would be to add
    # autover under 'test requires'?)
    - autover

test:
  imports:
    - pkg_depend
  commands:
    - tmpverify pkg_depend {{ environ['GIT_DESCRIBE_TAG'] }} {{ environ['GIT_DESCRIBE_NUMBER'] }} {{ environ['GIT_DESCRIBE_HASH'] }}

about:
  home: {{ sdata['url'] }}
  summary: {{ sdata['description'] }}
  license: {{ sdata['license'] }}
