#!/usr/bin/env python
# Import and print the library version and filesystem location for each Python package specified
#
# bash usage: $ pyver numpy pandas 
# python usage: >>> import pyver ; pyver("numpy","pandas")

from __future__ import print_function
import os.path, importlib

def pyver(*packages):
    """Import and print location and version information for specified Python packages"""
    for package in packages:
        loc = "not installed"
        ver = "unknown"
        
        try:
            module = importlib.import_module(package)
            loc =  os.path.dirname(module.__file__)

            try:
                ver = str(module.__version__)
            except Exception:
                pass
        
        except ImportError:
            pass
        
        print("{0:30} # {1}".format(package + "=" + ver,loc))


if __name__ == "__main__":
    import sys
    pyver(*(sys.argv[1:]))
