#!/usr/bin/env python

import sys
module_name = sys.argv[1]
module = __import__(module_name)

###############
# (a) pep440 compliant?
import pkg_resources._vendor.packaging.version as packaging_version
packaging_version.Version(module.__version__)

###############
# (b) following desired 'latest master' version scheme?
# v0.2.0-5-g85da374 --> 0.2.0.post5+g85da374
import subprocess
import os

GIT_VERSION = os.environ.get("GIT_VERSION")

if len(sys.argv)>2:
    v=sys.argv[2]
    commits=sys.argv[3]
    sha=sys.argv[4]
    print("Git info read from arguments: %s %s %s"%(v,commits,sha))
elif GIT_VERSION is not None:
    v,commits,sha=GIT_VERSION.split('-')
    print("Git info read from GIT_VERSION: %s %s %s"%(v,commits,sha))
else:
    desc=subprocess.check_output(['git','describe','--long']).decode('utf8').strip()
    v,commits,sha=desc.split('-')
    print("Git info collected from git in %s: %s %s %s"%(os.getcwd(),v,commits,sha))

expected_version=v[1::]
if int(commits) > 0:
    expected_version += '.post'+commits+"+"+sha;

assert module.__version__ == expected_version, '%s.__version__ %r does not match %r' % (module_name,module.__version__,expected_version)

###############
# (c) setup.py version matches __version__ (only relevant in a source dir)
try:
    print(os.getcwd())
    print(sys.path)
    import setup
    print(setup.__file__)
    assert module.__version__ == setup.setup_args['version'], '%s.__version__ %r does not match setup version %r'%(module_name,module.__version__, setup.setup_args['version'])
except ImportError:
    print("skipping setup.py check")
    import traceback
    traceback.print_exc()

