package:
  name: autover
  version: {{ environ['GIT_DESCRIBE_TAG'].lstrip('v') }}.{{ GIT_BUILD_STR }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - autover
  commands:
    # verify conda-installed autover
    - tmpverify {{ environ['GIT_DESCRIBE_TAG'] }} {{ environ['GIT_DESCRIBE_NUMBER'] }} {{ environ['GIT_DESCRIBE_HASH'] }}

about:
  home: https://github.com/ioam/autover
  summary: Autover provides consistent and up-to-date `__version__` strings for Python packages.
  license: BSD 3-Clause
